export const GLOBAL_TASKS = {
  book_read: {
    name: "Read 5x pages of a book",
    summary: "Read Book",
    points: 10,
    dailyLimit: 10,
    category: "Task",
    level: 1,
    maxLevel: 3,
    requiredCompletionsForNextLevel: 10,
    penalty: 5,
    numberLimit: 70,
    frequencyUnit: "days",
    weeklyFrequency: 70,
    hasExceptionalOption: true,
    selectedMode: "normal",
    hasTimesOption: false,
  },
  not_doing_shit: {
    name: "Not doing shit habit",
    summary: "No Shit Habit",
    points: 50,
    dailyLimit: 1,
    category: "Task",
    level: 1,
    maxLevel: 3,
    requiredCompletionsForNextLevel: 10,
    penaltyPoints: 50,
    numberLimit: 7,
    frequencyUnit: "days",
    weeklyFrequency: 7,
    hasExceptionalOption: true,
    hasTimesOption: false,
  },
  quran_read: {
    name: "Quran : Read robo3x hizb",
    summary: "Read Quoran",
    points: 10,
    dailyLimit: 10,
    category: "Task",
    level: 1,
    maxLevel: 3,
    requiredCompletionsForNextLevel: 10,
    penalty: 5,
    numberLimit: 70,
    frequencyUnit: "days",
    weeklyFrequency: 70,
    hasExceptionalOption: true,
    selectedMode: "normal",
    hasTimesOption: false,
  },
  sport_exercise: {
    name: "Sport : Exercice for 20x min",
    summary: "Sport",
    points: 10,
    dailyLimit: 10,
    category: "Task",
    level: 1,
    maxLevel: 3,
    requiredCompletionsForNextLevel: 10,
    penalty: 5,
    numberLimit: 30,
    frequencyUnit: "days",
    weeklyFrequency: 30,
    hasExceptionalOption: false,
    hasTimesOption: false,
  },
  prayer_mosque: {
    name: "Praye x times At The Mosque",
    summary: "Mosque Prayer",
    points: 10,
    dailyLimit: 5,
    category: "Task",
    level: 1,
    maxLevel: 3,
    requiredCompletionsForNextLevel: 10,
    penalty: 5,
    numberLimit: 35,
    frequencyUnit: "times",
    requiredCompletions: 35,
    hasExceptionalOption: true,
    selectedMode: "normal",
    hasTimesOption: false,
  },
  quran_listen: {
    name: "listen to quoran",
    points: 10,
    dailyLimit: 10,
    category: "Task",
    penalty: 5,
    numberLimit: 2,
    frequencyUnit: "days",
    weeklyFrequency: 2,
    hasExceptionalOption: false,
    hasTimesOption: false,
  },
  improvement_15min: {
    name: "15 Min Improvement",
    summary: "Improvement",
    points: 10,
    dailyLimit: 10,
    category: "Task",
    level: 1,
    maxLevel: 3,
    requiredCompletionsForNextLevel: 10,
    penalty: 5,
    numberLimit: 70,
    frequencyUnit: "days",
    weeklyFrequency: 70,
    hasExceptionalOption: false,
    hasTimesOption: false,
  },
  wake_up_early: {
    name: "Wake up early",
    summary: "Wake up early",
    points: 10,
    dailyLimit: 1,
    category: "Task",
    penalty: 5,
    numberLimit: 6,
    frequencyUnit: "days",
    weeklyFrequency: 6,
    hasExceptionalOption: false,
    hasTimesOption: false,
  },
  shaf3_witr_20: {
    name: "20 pts الشفع و الوتر",
    summary: "الشفع و الوتر20",
    points: 10,
    dailyLimit: 1,
    category: "Bonus",
    penalty: 5,
    numberLimit: 1,
    frequencyUnit: "days",
    weeklyFrequency: 1,
    hasExceptionalOption: false,
    hasTimesOption: false,
  },
  shaf3_witr_40: {
    name: "40 pts الشفع و الوتر",
    summary: "الشفع و الوتر40",
    points: 30,
    dailyLimit: 1,
    category: "Bonus",
    penalty: 5,
    numberLimit: 1,
    frequencyUnit: "days",
    weeklyFrequency: 1,
    hasExceptionalOption: false,
    hasTimesOption: false,
  },
  presentation: {
    name: "Presentation",
    summary: "Presentation",
    points: 40,
    dailyLimit: 1,
    category: "Bonus",
    penalty: 5,
    numberLimit: 1,
    frequencyUnit: "days",
    weeklyFrequency: 1,
    hasExceptionalOption: false,
    hasTimesOption: false,
  },
  no_social_media: {
    name: "One day no social Media",
    summary: "No social media",
    points: 20,
    dailyLimit: 1,
    category: "Bonus",
    penalty: 5,
    numberLimit: 1,
    frequencyUnit: "days",
    weeklyFrequency: 1,
    hasExceptionalOption: false,
    hasTimesOption: false,
  },
  khatm_quran: {
    name: "ختم القرأن",
    summary: "ختم القرأن",
    points: 20,
    dailyLimit: 1,
    category: "Bonus",
    penalty: 5,
    numberLimit: 1,
    frequencyUnit: "days",
    weeklyFrequency: 1,
    hasExceptionalOption: false,
    hasTimesOption: false,
  },
  weekly_meeting: {
    name: "Attend the Weekly meeting",
    summary: "Weekly Meeting",
    points: 10,
    dailyLimit: 1,
    category: "Bonus",
    penalty: 5,
    numberLimit: 1,
    frequencyUnit: "days",
    weeklyFrequency: 1,
    hasExceptionalOption: false,
    hasTimesOption: false,
  },
};
